#!/bin/bash

#
# Copyright © 2021 Aram Meem Company Limited. All Rights Reserved.
#

# Please note: code generated by swagger-codegen was slightly modified as genuine result doesn't work.
docker run -u $(id -u):$(id -g) --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3:3.0.27 \
   generate \
   -i /local/api-spec/merchant-public-api-orders.json \
   -o /local/public-api-orders-client \
   -l java  \
   --group-id=com.am.rest.client \
   --artifact-id=client-orders-api \
   --model-package=com.am.rest.client.orders.model \
   --api-package=com.am.rest.client.orders.api \
   --additional-properties library=resteasy,java8=true,hideGenerationTimestamp=true

docker run -u $(id -u):$(id -g) --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3:3.0.27 \
   generate \
   -i /local/api-spec/catalog-swagger.json \
   -o /local/catalog-api-client \
   -l java  \
   --group-id=com.am.rest.client \
   --artifact-id=client-catalog-api \
   --model-package=com.am.rest.client.catalog.model \
   --api-package=com.am.rest.client.catalog.api \
   --additional-properties library=resteasy,java8=true,hideGenerationTimestamp=true
