/*
 * ToYou's public API:  Orders
 * Allows to get notified about new orders, order status changes and retrieve order details.<br/> As soon as a driver has been assigned to the order, it becomes available to retrieve by 3rd party. It means that driver is already on the way to pickup the order. The status of the order will change during the delivery. ToYou provides the information on each status change of the delivery
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.am.rest.client.orders.api;

import com.am.rest.client.orders.ApiException;
import org.threeten.bp.OffsetDateTime;
import com.am.rest.client.orders.model.OrderChangeData;
import com.am.rest.client.orders.model.OrderData;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrdersResourceApi
 */
@Ignore
public class OrdersResourceApiTest {

    private final OrdersResourceApi api = new OrdersResourceApi();

    /**
     * Get Order data by ID
     *
     * Use Order ID from order change data to get Order details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderByIdByUsingGETTest() throws ApiException {
        UUID orderId = null;
        OrderData response = api.orderByIdByUsingGET(orderId);

        // TODO: test validations
    }
    /**
     * Get Order change data by date time period
     *
     * Search the orders created or with the changed status within the date time interval.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderListByUsingGETTest() throws ApiException {
        OffsetDateTime fromDateTime = null;
        OffsetDateTime toDateTime = null;
        List<OrderChangeData> response = api.orderListByUsingGET(fromDateTime, toDateTime);

        // TODO: test validations
    }
    /**
     * Set Order as Failed
     *
     * ToYou API does not support the order cancellation. If 3rd party system is unable to create the retrieved order it should set it as Failed. Failed orders appear on Merchant Portal/Failed orders page in ToYou system
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setOrderFailedUsingPUTTest() throws ApiException {
        UUID orderId = null;
        String failureReason = null;
        api.setOrderFailedUsingPUT(orderId, failureReason);

        // TODO: test validations
    }
}
