/*
 * ToYou's public API:  Orders
 * Allows to get notified about new orders, order status changes and retrieve order details.<br/> As soon as a driver has been assigned to the order, it becomes available to retrieve by 3rd party. It means that driver is already on the way to pickup the order. The status of the order will change during the delivery. ToYou provides the information on each status change of the delivery
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.am.rest.client.orders.model;

import java.util.Objects;
import java.util.Arrays;
import com.am.rest.client.orders.model.OptionValueOrderedWithProduct;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * OrderLineWithProduct
 */


public class OrderLineWithProduct {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("quantity")
  private BigDecimal quantity = null;

  @JsonProperty("price")
  private BigDecimal price = null;

  @JsonProperty("note")
  private String note = null;

  @JsonProperty("productId")
  private UUID productId = null;

  @JsonProperty("productOptionsValues")
  private List<OptionValueOrderedWithProduct> productOptionsValues = null;

  public OrderLineWithProduct name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Product name in selected language (en or ar)
   * @return name
  **/
  @Schema(required = true, description = "Product name in selected language (en or ar)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrderLineWithProduct quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Number of products ordered
   * @return quantity
  **/
  @Schema(required = true, description = "Number of products ordered")
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public OrderLineWithProduct price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Product&#x27;s price (tax exclusive)
   * @return price
  **/
  @Schema(required = true, description = "Product's price (tax exclusive)")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public OrderLineWithProduct note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Ordered item note from Customer
   * @return note
  **/
  @Schema(required = true, description = "Ordered item note from Customer")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public OrderLineWithProduct productId(UUID productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Product’s unique ID in ToYou system
   * @return productId
  **/
  @Schema(required = true, description = "Product’s unique ID in ToYou system")
  public UUID getProductId() {
    return productId;
  }

  public void setProductId(UUID productId) {
    this.productId = productId;
  }

  public OrderLineWithProduct productOptionsValues(List<OptionValueOrderedWithProduct> productOptionsValues) {
    this.productOptionsValues = productOptionsValues;
    return this;
  }

  public OrderLineWithProduct addProductOptionsValuesItem(OptionValueOrderedWithProduct productOptionsValuesItem) {
    if (this.productOptionsValues == null) {
      this.productOptionsValues = new ArrayList<>();
    }
    this.productOptionsValues.add(productOptionsValuesItem);
    return this;
  }

   /**
   * Get productOptionsValues
   * @return productOptionsValues
  **/
  @Schema(description = "")
  public List<OptionValueOrderedWithProduct> getProductOptionsValues() {
    return productOptionsValues;
  }

  public void setProductOptionsValues(List<OptionValueOrderedWithProduct> productOptionsValues) {
    this.productOptionsValues = productOptionsValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderLineWithProduct orderLineWithProduct = (OrderLineWithProduct) o;
    return Objects.equals(this.name, orderLineWithProduct.name) &&
        Objects.equals(this.quantity, orderLineWithProduct.quantity) &&
        Objects.equals(this.price, orderLineWithProduct.price) &&
        Objects.equals(this.note, orderLineWithProduct.note) &&
        Objects.equals(this.productId, orderLineWithProduct.productId) &&
        Objects.equals(this.productOptionsValues, orderLineWithProduct.productOptionsValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, quantity, price, note, productId, productOptionsValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderLineWithProduct {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    productOptionsValues: ").append(toIndentedString(productOptionsValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
