/*
 * ToYou's public API:  Orders
 * Allows to get notified about new orders, order status changes and retrieve order details.<br/> As soon as a driver has been assigned to the order, it becomes available to retrieve by 3rd party. It means that driver is already on the way to pickup the order. The status of the order will change during the delivery. ToYou provides the information on each status change of the delivery
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.am.rest.client.orders.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * OrderDataOrderTotal
 */


public class OrderDataOrderTotal {
  @JsonProperty("basketVAT")
  private BigDecimal basketVAT = null;

  @JsonProperty("total")
  private BigDecimal total = null;

  public OrderDataOrderTotal basketVAT(BigDecimal basketVAT) {
    this.basketVAT = basketVAT;
    return this;
  }

   /**
   * VAT amount calculated from Basket total amount
   * @return basketVAT
  **/
  @Schema(description = "VAT amount calculated from Basket total amount")
  public BigDecimal getBasketVAT() {
    return basketVAT;
  }

  public void setBasketVAT(BigDecimal basketVAT) {
    this.basketVAT = basketVAT;
  }

  public OrderDataOrderTotal total(BigDecimal total) {
    this.total = total;
    return this;
  }

   /**
   * Total basket amount including VAT
   * @return total
  **/
  @Schema(description = "Total basket amount including VAT")
  public BigDecimal getTotal() {
    return total;
  }

  public void setTotal(BigDecimal total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDataOrderTotal orderDataOrderTotal = (OrderDataOrderTotal) o;
    return Objects.equals(this.basketVAT, orderDataOrderTotal.basketVAT) &&
        Objects.equals(this.total, orderDataOrderTotal.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basketVAT, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDataOrderTotal {\n");
    
    sb.append("    basketVAT: ").append(toIndentedString(basketVAT)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
