/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.am.rest.client.catalog.api;

import com.am.rest.client.catalog.ApiException;
import com.am.rest.client.catalog.model.AuthTokensDto;
import com.am.rest.client.catalog.model.LoginData;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MerchantUserResourceApi
 */
@Ignore
public class MerchantUserResourceApiTest {

    private final MerchantUserResourceApi api = new MerchantUserResourceApi();

    /**
     * Get refreshed tokens
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTokensUsingGETTest() throws ApiException {
        String authorization = null;
        AuthTokensDto response = api.getTokensUsingGET(authorization);

        // TODO: test validations
    }
    /**
     * Generate tokens for existing merchant user by email and password
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTokensUsingPOSTTest() throws ApiException {
        LoginData body = null;
        AuthTokensDto response = api.getTokensUsingPOST(body);

        // TODO: test validations
    }
}
